// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/smart-pantry-refresh/Current.tsx": () => import("../components/mockups/smart-pantry-refresh/Current.tsx")
};
